### PR TITLE
Update alienship-shortcodes.php

### PR DESCRIPTION
**Pull request by obcidio**
Added [row] and [col] shortcodes.

### CODE REVIEW

**Comment by mindctrl** [comment]
@obcidio thanks for the PR. Mind updating it to remove the update checker entirely? That's something I've been planning to do because I don't want to serve updates from my site for this plugin any longer.

**Comment by obcidio** [comment]
Yeah, man - I'll take care of it next week.

**Comment by obcidio** [comment]
Removed the lines to load the update checker.

**Comment by mindctrl** [comment]
Awesome. Thanks @obcidio! 💯 for also removing `extract()`.

**Pull request merged**
